# Generated by Django 3.2.4 on 2021-06-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='about',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='welcome_text',
        ),
    ]
