# Generated by Django 3.2.4 on 2021-07-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_testimonies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(blank=True, max_length=225)),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('pending', 'pending'), ('Closed', 'Closed')], default='New', max_length=10)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
