# Generated by Django 3.2.4 on 2021-07-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('details', models.CharField(blank=True, max_length=900, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewimg', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('review', models.CharField(blank=True, max_length=900, null=True)),
                ('reviewimg2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name2', models.CharField(blank=True, max_length=30, null=True)),
                ('date2', models.CharField(blank=True, max_length=20, null=True)),
                ('review2', models.CharField(blank=True, max_length=900, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.portfolio')),
            ],
        ),
    ]
